export const CHANNEL_REPOSITORY = 'CHANNEL_REPOSITORY';

export const ELEMENTS_REPOSITORY = 'ELEMENTS_REPOSITORY';

export const MESSAGE_REPOSITORY = 'MESSAGE_REPOSITORY';

export const PERSON_REPOSITORY = 'PERSON_REPOSITORY';

export const DATA_SOURCE = 'DATA_SOURCE';
