version: "3"
services:
  database:
    image: "postgres:latest"
    ports:
      - ${POSTGRES_DEFAULT_PORT}:${POSTGRES_DEFAULT_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pg-data/:/var/lib/postgresql/data/
  test_database:
    image: "postgres:latest"
    ports:
      - ${POSTGRES_TEST_PORT}:${POSTGRES_DEFAULT_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}