swagger: "2.0"
info:
  description: "This API facilitates the ability to track who gives and receives shoutouts at DEPT®."
  version: "1.0.0"
  title: "DEPT® Shoutouts"
host: "TBD"
basePath: "/api"
paths:
  /latest-shoutouts:
    get:
      summary: "Returns the 10 most recent shoutouts"
      tags: 
      - shoutouts
      produces:
      - "application/json"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Shoutout"
        "401":
          description: "Unauthorized"
        "500":
          description: "Unexpected Error"
      security:
      - api_key: []
  /shoutouts-by-timeframe:
    get:
      summary: "Returns all shoutouts for the given month (or past 12 months if no valid month given)"
      tags: 
      - shoutouts
      produces:
      - "application/json"
      parameters:
      - name: "month"
        in: "query"
        required: false
        type: "number"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Shoutout"
        "401":
          description: "Unauthorized"
        "500":
          description: "Unexpected Error"
      security:
      - api_key: []
  /profile/search:
    get:
      summary: "Searches for people given name or email and returns their user info"
      tags: 
      - profile
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "partial or full name of a person"
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: "partial or full email address of a person"
        required: false
        type: "string"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Profile"
        "400":
          description: "Bad Request (Valid \"name\" or \"email\" Param Required)"
        "401":
          description: "Unauthorized"
        "500":
          description: "Unexpected Error"
      security:
      - api_key: []
  /profile/{id}:
    get:
      summary: "Returns information about a person including shoutouts given and received"
      tags: 
      - profile
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "unique ID of a person"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            $ref: "#/definitions/Profile"
        "400":
          description: "Bad Request (Valid \"id\" Param Required)"
        "401":
          description: "Unauthorized"
        "500":
          description: "Unexpected Error"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Person:
    type: "object"
    properties:
      employeeId:
        type: "number"
      email:
        type: "string"
      team:
        type: "string"
      country:
        type: "string"
      name:
        type: "string"
  Shoutout:
    type: "object"
    properties:
      author:
        $ref: "#/definitions/Person"
      recipients:
        type: "array"
        items:
          $ref: "#/definitions/Person"
      text:
        type: "string"
      createDate:
        type: "string"
  Profile:
    type: "object"
    properties:
      userInfo:
        $ref: "#/definitions/Person"
      shoutoutsGiven:
        type: "array"
        items:
          $ref: "#/definitions/Shoutout"
      shoutoutsRecevied:
        type: "array"
        items:
          $ref: "#/definitions/Shoutout"