const userSkills: any = [
  {
    email: 'ed.lewis@deptagency.com',
    languages: ['React Native', 'JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'Python'],
    platforms: ['Shopify', 'AWS'],
  },
  {
    email: 'louis.huerta-blake@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'Rails'],
    platforms: [],
  },
  {
    email: 'keegan.sands@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Angular', 'Java'],
    platforms: ['Adobe Experience Manager', 'AWS'],
  },
  {
    email: 'olivia.reeve@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'Node.js', 'Rails'],
    platforms: ['Adobe Experience Manager'],
  },
  {
    email: 'gleb.raytsin@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', '.NET / C#'],
    platforms: [],
  },
  {
    email: 'jay.canty@deptagency.com',
    languages: ['iOS / Swift', 'React Native'],
    platforms: ['Contentful'],
  },
  {
    email: 'kathy.king@deptagency.com',
    languages: ['Vue', 'Node.js', 'Golang', 'Java'],
    platforms: ['AWS'],
  },
  {
    email: 'jeff.rosenberg@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'Python', 'PHP'],
    platforms: ['Optimizely'],
  },
  {
    email: 'ian.pirro@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js', '.NET / C#', 'Python'],
    platforms: ['AWS', 'GCP'],
  },
  {
    email: 'jfisher@basicagency.com',
    languages: ['React Native', 'JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'PHP'],
    platforms: ['Contentful', 'ContentStack', 'Shopify', 'AWS'],
  },
  {
    email: 'matt.brooks@deptagency.com',
    languages: ['React Native', 'JavaScript', 'TypeScript', 'React', '.NET / C#'],
    platforms: [],
  },
  {
    email: 'dylan.hofmann@deptagency.com',
    languages: [
      'iOS / Swift',
      'JavaScript',
      'TypeScript',
      'Vue',
      'React',
      'Node.js',
      'PHP',
      'Cypress',
    ],
    platforms: ['Drupal / Acquia', 'AWS'],
  },
  {
    email: 'jonah.jolley@deptagency.com',
    languages: [
      'React Native',
      'JavaScript',
      'TypeScript',
      'React',
      'Node.js',
      '.NET / C#',
      'Rails',
      'Golang',
      'Python',
      'Terraform',
    ],
    platforms: ['AWS'],
  },
  {
    email: 'mike.sampson@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js'],
    platforms: ['AWS'],
  },
  {
    email: 'aj.schnore@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Golang', 'Python', 'PHP'],
    platforms: ['AWS', 'Azure', 'GCP'],
  },
  {
    email: 'kojo.asmah@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Selenium', 'Cypress'],
    platforms: ['AWS'],
  },
  {
    email: 'lucas.parzych@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'Snowflake', 'Terraform'],
    platforms: ['AWS', 'GCP'],
  },
  {
    email: 'lara.pollack@deptagency.com',
    languages: ['React Native', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'PHP'],
    platforms: ['Contentful', 'AWS'],
  },
  {
    email: 'ben.andrews@deptagency.com',
    languages: ['Python', 'Java'],
    platforms: ['AWS'],
  },
  {
    email: 'alex.mohr@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'Java', 'Cypress'],
    platforms: ['Drupal / Acquia', 'Contentful', 'AWS'],
  },
  {
    email: 'richard.reece@deptagency.com',
    languages: ['Android / Kotlin', 'Java'],
    platforms: ['AWS', 'GCP'],
  },
  {
    email: 'billy.ferris@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js'],
    platforms: ['Contentful', 'AWS'],
  },
  {
    email: 'dallas.huggins@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js'],
    platforms: ['Optimizely', 'Contentful', 'AWS', 'GCP'],
  },
  {
    email: 'ross.perry@deptagency.com',
    languages: [
      'JavaScript',
      'TypeScript',
      'Vue',
      'React',
      'Angular',
      'Node.js',
      'Rails',
      'Python',
    ],
    platforms: [],
  },
  {
    email: 'daniel.paterson@deptagency.com',
    languages: ['Node.js', '.NET / C#', 'Java'],
    platforms: ['Sitecore', 'Contentful', 'CommerceTools'],
  },
  {
    email: 'nalcantara@basicagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'Rails', 'PHP'],
    platforms: ['Contentful', 'Shopify'],
  },
  {
    email: 'jordan.richards@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', '.NET / C#'],
    platforms: ['Sitecore'],
  },
  {
    email: 'cliff.anderson@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Rails', 'Java', 'PHP'],
    platforms: [],
  },
  {
    email: 'ian.vossoughi@deptagency.com',
    languages: ['Android / Kotlin', 'JavaScript', 'TypeScript', 'Python', 'Java', 'Spark'],
    platforms: ['AWS', 'Azure'],
  },
  {
    email: 'david.murphy@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Angular', 'Node.js', '.NET / C#'],
    platforms: ['AWS', 'Azure', 'GCP'],
  },
  {
    email: 'tom.simm@deptagency.com',
    languages: ['Terraform'],
    platforms: ['AWS', 'Azure'],
  },
  {
    email: 'james.simm@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js', '.NET / C#'],
    platforms: ['Sitecore', 'CommerceTools', 'AWS', 'Azure'],
  },
  {
    email: 'tom.hartley@deptagency.com',
    languages: ['React Native', 'JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'PHP'],
    platforms: ['AWS'],
  },
  {
    email: 'pete.davies@deptagency.com',
    languages: ['.NET / C#', 'Rails', 'Selenium'],
    platforms: ['Sitecore', 'Optimizely', 'Contentful', 'Shopify', 'Azure'],
  },
  {
    email: 'dean.spooner@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React'],
    platforms: ['Optimizely', 'Contentful'],
  },
  {
    email: 'jay.wem@deptagency.com',
    languages: ['React Native', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'Rails', 'Python'],
    platforms: ['Optimizely'],
  },
  {
    email: 'anthony.macneil@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', '.NET / C#'],
    platforms: ['Sitecore', 'Optimizely', 'Contentful'],
  },
  {
    email: 'stefan.croft@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'Node.js', 'PHP'],
    platforms: [],
  },
  {
    email: 'sam.west@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', '.NET / C#', 'Selenium'],
    platforms: ['Sitecore', 'Optimizely', 'Kentico / Kontent', 'AWS', 'Azure'],
  },
  {
    email: 'miguel.guedelha@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Angular', '.NET / C#'],
    platforms: ['Sitecore', 'Contentful', 'AWS', 'Azure'],
  },
  {
    email: 'chris.eccles@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Angular', 'Node.js', '.NET / C#'],
    platforms: ['Optimizely', 'Contentful', 'AWS', 'Azure'],
  },
  {
    email: 'dalton.walsh@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'PHP'],
    platforms: [],
  },
  {
    email: 'daniel.pang@deptagency.com',
    languages: ['Python', 'Java', 'Terraform'],
    platforms: ['AWS', 'Azure', 'GCP'],
  },
  {
    email: 'matt.falconer@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js'],
    platforms: ['Contentful'],
  },
  {
    email: 'can.madran@bytelondon.com',
    languages: [
      'Android / Kotlin',
      'React Native',
      'Flutter',
      'JavaScript',
      'TypeScript',
      'React',
      'Node.js',
      'Python',
      'Java',
      'BigQuery',
      'Terraform',
      'Selenium',
    ],
    platforms: ['AWS', 'Azure', 'GCP'],
  },
  {
    email: 'howard.bayliss@deptagency.com',
    languages: ['.NET / C#', 'Selenium'],
    platforms: ['AWS', 'Azure'],
  },
  {
    email: 'stuart.bronk@deptagency.com',
    languages: ['JavaScript', 'TypeScript', '.NET / C#'],
    platforms: ['Sitecore', 'AWS', 'Azure'],
  },
  {
    email: 'phil.robinson@deptagency.com',
    languages: ['.NET / C#'],
    platforms: ['Azure', 'GCP'],
  },
  {
    email: 'andy.blyth@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', '.NET / C#'],
    platforms: ['Optimizely', 'Contentful', 'AWS', 'Azure'],
  },
  {
    email: 'shane.prendergast@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'PHP', 'Cypress'],
    platforms: ['Contentful', 'AWS', 'Azure'],
  },
  {
    email: 'sam.harrison@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React'],
    platforms: ['Optimizely', 'Contentful'],
  },
  {
    email: 'joe.baker@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Angular', 'Node.js'],
    platforms: ['Drupal / Acquia', 'Contentful', 'Magento / Adobe Commerce Cloud'],
  },
  {
    email: 'callum.fowler@bytelondon.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js'],
    platforms: [],
  },
  {
    email: 'nathan.ouriach@deptagency.com',
    languages: ['.NET / C#'],
    platforms: ['Optimizely'],
  },
  {
    email: 'daniel.robinson@deptagency.com',
    languages: [
      'Android / Kotlin',
      'iOS / Swift',
      'JavaScript',
      'TypeScript',
      'Vue',
      'React',
      'Angular',
      'Node.js',
      '.NET / C#',
      'Cypress',
    ],
    platforms: ['Contentful', 'AWS'],
  },
  {
    email: 'tim.nokes@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'PHP'],
    platforms: ['Contentful', 'Salesforce Commerce Cloud B2C', 'Shopify', 'AWS', 'Azure'],
  },
  {
    email: 'mand.cashin@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Angular', 'Node.js'],
    platforms: ['Contentful', 'Shopify', 'Magento / Adobe Commerce Cloud'],
  },
  {
    email: 'antonio.mifsud@feedagency.com',
    languages: ['JavaScript', 'TypeScript'],
    platforms: ['Adobe Experience Manager', 'Magento / Adobe Commerce Cloud'],
  },
  {
    email: 'louis.smullen@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Node.js', 'PHP'],
    platforms: ['Shopify'],
  },
  {
    email: 'james.rigby@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'Java'],
    platforms: [],
  },
  {
    email: 'ashley@bytelondon.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js'],
    platforms: ['AWS', 'Azure', 'GCP'],
  },
  {
    email: 'alberto.fernandezvadillo@deptagency.com',
    languages: ['.NET / C#'],
    platforms: ['Optimizely', 'Kentico / Kontent', 'AWS', 'Azure'],
  },
  {
    email: 'chris.maltby@feedagency.com',
    languages: [
      'JavaScript',
      'TypeScript',
      'React',
      'Node.js',
      'Golang',
      'Python',
      'Java',
      'PHP',
      'Selenium',
      'Cypress',
    ],
    platforms: ['Drupal / Acquia', 'AWS'],
  },
  {
    email: 'richard.coates@bytelondon.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'PHP'],
    platforms: ['AWS', 'GCP'],
  },
  {
    email: 'sergio.candela-ferrandez@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'PHP'],
    platforms: ['AWS'],
  },
  {
    email: 'anna.kovecsi@deptagency.com',
    languages: ['.NET / C#'],
    platforms: ['Sitecore', 'Optimizely', 'AWS'],
  },
  {
    email: 'lewis.smith@deptagency.com',
    languages: ['JavaScript', 'TypeScript'],
    platforms: ['Adobe Experience Manager'],
  },
  {
    email: 'dan.bridges@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js'],
    platforms: [],
  },
  {
    email: 'nick.martinez@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Angular'],
    platforms: ['Optimizely', 'Contentful'],
  },
  {
    email: 'tspinks@basicagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React', 'Python', 'PHP'],
    platforms: [
      'Adobe Experience Manager',
      'Optimizely',
      'Drupal / Acquia',
      'Contentful',
      'Shopify',
      'Magento / Adobe Commerce Cloud',
      'AWS',
    ],
  },
  {
    email: 'alejandro.reinel@bytelondon.com',
    languages: ['JavaScript', 'TypeScript', 'Node.js', 'Python', 'BigQuery'],
    platforms: ['AWS'],
  },
  {
    email: 'benjamin.tellier@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js'],
    platforms: ['Drupal / Acquia'],
  },
  {
    email: 'alex.ludlow@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Cypress'],
    platforms: ['Contentful'],
  },
  {
    email: 'utkarsha.vibhute@deptagency.com',
    languages: ['Java', 'Selenium'],
    platforms: ['Sitecore', 'Optimizely', 'Contentful'],
  },
  {
    email: 'matt.meadows@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'Vue', 'React'],
    platforms: ['Optimizely', 'Contentful'],
  },
  {
    email: 'michelle.brown@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'PHP'],
    platforms: ['Adobe Experience Manager', 'AWS'],
  },
  {
    email: 'helder.goncalves@feedagency.com',
    languages: ['React'],
    platforms: ['AWS'],
  },
  {
    email: 'mickey.saeed@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Java'],
    platforms: ['Salesforce Commerce Cloud B2C', 'Salesforce Commerce Cloud B2B', 'Shopify', 'AWS'],
  },
  {
    email: 'conrad.davis@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'PHP'],
    platforms: [],
  },
  {
    email: 'josh.towers@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'PHP'],
    platforms: ['Optimizely', 'Contentful', 'Shopify'],
  },
  {
    email: 'mark.cassidy@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React'],
    platforms: ['Sitecore', 'Optimizely', 'Contentful', 'Azure'],
  },
  {
    email: 'tom.lerendu@deptagency.com',
    languages: [
      'iOS / Swift',
      'React Native',
      'JavaScript',
      'TypeScript',
      'Vue',
      'React',
      'Angular',
      'Node.js',
      'PHP',
    ],
    platforms: ['Contentful'],
  },
  {
    email: 'ken.chan@deptagency.com',
    languages: ['Terraform'],
    platforms: ['AWS', 'Azure'],
  },
  {
    email: 'sarah.penney@feedagency.com',
    languages: ['JavaScript', 'TypeScript', 'Angular'],
    platforms: ['AWS'],
  },
  {
    email: 'aisha.ghazanfar@feedagency.com',
    languages: ['JavaScript', 'TypeScript'],
    platforms: [],
  },
  {
    email: 'greg.wakefield@bytelondon.com',
    languages: ['JavaScript', 'TypeScript', 'React', 'Node.js'],
    platforms: [],
  },
  {
    email: 'tim.iland@deptagency.com',
    languages: ['JavaScript', 'TypeScript', 'React'],
    platforms: ['Optimizely', 'AWS'],
  },
];

export default userSkills;
