name: Deploy App

on:
  pull_request:
    types:
      - closed
    branches:
      - dummy_staging
      - dummy_main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy staging
        if: github.base_ref == 'dummy_staging'
        run: echo staging...
      - name: Deploy production
        if: github.base_ref == 'dummy_main'
        run: echo prodding...

      #- uses: actions/checkout@v2
      #- uses: superfly/flyctl-actions/setup-flyctl@master
      #- run: flyctl deploy --remote-only
      #  env:
      #   FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

