name: Lint and Test

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - staging
      - main
      - staging #will delete

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm install
      - run: npm run lint
      - name: Start database instance for testing
        uses: harmon758/postgresql-action@v1
      - name: Create/synchronize database tables before tests
        run: npm run test:init
      - run: npm run test