name: Lint and Test

on:
  pull_request:
    types:
      - opened
    branches:
      - 'dummy_staging'

jobs:
  build:
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm install
      - run: npm run lint
      - name: Start database instance for testing
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: ${{ env.POSTGRES_DB }}
          postgresql user: ${{ env.POSTGRES_USER }}
          postgresql password: ${{ env.POSTGRES_PASSWORD }}
      - run: npm run test
        env:
          SYNCHRONIZE: true