name: Deploy to Production

on:
  pull_request:
    types:
      - closed
    branches: 'dummy_main'

jobs:
  setup_env:
    uses: ./.github/workflows/setup-env
  
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Build and deploy staging
      run: echo prodding...
    ###