name: Deploy to Staging

on:
  pull_request:
    types:
      - closed
    branches: 'dummy_staging'

jobs:  
  build_and_deploy:
    uses: ./.github/workflows/setup-env.yml

    steps:
    - name: Build and deploy staging
      run: echo staging...
    ###